version: '3.8'

services:
  api:
    build: .
    volumes:
      - .:/app:cached
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
    ports:
      - 8000:8000
    depends_on:
      - db
    environment: &api-environment
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      REDIS_HOST: redis
    command: sh -c "alembic upgrade head
      && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: postgres:15.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  rabbitmq:
    image: rabbitmq:3.10.7-management
    restart: always

    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1

  worker:
    build: .
    volumes:
      - .:/app:cached
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
    environment:
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      REDIS_HOST: redis
      RABBITMQ_HOST: rabbitmq
    command: bash -c "celery -A src.celery_worker.celery beat --loglevel=info & celery -A src.celery_worker.celery worker --concurrency=1 --loglevel=info -B"
    depends_on:
      - api
      - redis
      - rabbitmq

  redis:
    image: redis
    ports:
      - 6379:6379
