version: '3.8'

services:
  api_test:
    build: .
    volumes:
      - .:/app:cached
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
    ports:
      - 5000:8000
    depends_on:
      db_test:
        condition: service_healthy
    environment: &api-environment
      DATABASE_NAME: postgres_test
      DATABASE_USER: postgres_test
      DATABASE_PASSWORD: postgres_test
      DATABASE_HOST: db_test
      REDIS_HOST: redis_test
      DATABASE_PORT: 5432
    command: sh -c "alembic upgrade head
      && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload --workers=3"

  db_test:
    image: postgres:15.1-alpine
    ports:
      - 5499:5432
    environment:
      POSTGRES_USER: postgres_test
      POSTGRES_PASSWORD: postgres_test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres_test", "-d", "postgres_test"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s

  redis_test:
    image: redis
    ports:
      - 6399:6379
