"""update tables5

Revision ID: 02fcfb6f8dbd
Revises: 54c91ea5a89c
Create Date: 2023-07-24 01:26:24.152713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02fcfb6f8dbd'
down_revision = '54c91ea5a89c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'dishes', ['submenu_id', 'title', 'description', 'price'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dishes', type_='unique')
    # ### end Alembic commands ###
