"""update tables3

Revision ID: 3f85b41c111c
Revises: b1f33df29148
Create Date: 2023-07-24 01:21:25.095505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f85b41c111c'
down_revision = 'b1f33df29148'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
