"""update tables4

Revision ID: 54c91ea5a89c
Revises: 3f85b41c111c
Create Date: 2023-07-24 01:23:18.748784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54c91ea5a89c'
down_revision = '3f85b41c111c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dishes_submenu_id_fkey', 'dishes', type_='foreignkey')
    op.create_foreign_key(None, 'dishes', 'submenus', ['submenu_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('submenus_menu_id_fkey', 'submenus', type_='foreignkey')
    op.create_foreign_key(None, 'submenus', 'menus', ['menu_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submenus', type_='foreignkey')
    op.create_foreign_key('submenus_menu_id_fkey', 'submenus', 'menus', ['menu_id'], ['id'])
    op.drop_constraint(None, 'dishes', type_='foreignkey')
    op.create_foreign_key('dishes_submenu_id_fkey', 'dishes', 'submenus', ['submenu_id'], ['id'])
    # ### end Alembic commands ###
