"""update tables

Revision ID: 5db2dfbbfdaf
Revises: 517308b55474
Create Date: 2023-07-22 15:23:31.077387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5db2dfbbfdaf'
down_revision = '517308b55474'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('title', sa.String(), nullable=True))
    op.add_column('dishes', sa.Column('description', sa.String(), nullable=True))
    op.drop_constraint('dishes_submenu_id_name_price_key', 'dishes', type_='unique')
    op.create_unique_constraint(None, 'dishes', ['submenu_id', 'title', 'description', 'price'])
    op.drop_column('dishes', 'name')
    op.add_column('menus', sa.Column('title', sa.String(), nullable=True))
    op.add_column('menus', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('menus', 'name')
    op.add_column('submenus', sa.Column('title', sa.String(), nullable=True))
    op.add_column('submenus', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('submenus', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submenus', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('submenus', 'description')
    op.drop_column('submenus', 'title')
    op.add_column('menus', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('menus', 'description')
    op.drop_column('menus', 'title')
    op.add_column('dishes', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'dishes', type_='unique')
    op.create_unique_constraint('dishes_submenu_id_name_price_key', 'dishes', ['submenu_id', 'name', 'price'])
    op.drop_column('dishes', 'description')
    op.drop_column('dishes', 'title')
    # ### end Alembic commands ###
